[package]
name = "makepad_gen_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_converter = { path = "../../converter" }
gen_utils = { path = "../../utils" }
gen_parser = { path = "../../parser" }
rssyin = { path = "../../middleware/rssyin" }
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52", features = ["full", "extra-traits"] }
which = "6.0.1"
toml_edit = "0.22.12"
lazy_static = "1.5.0"
walkdir = "2.5.0"
gen_mk_script_objs = { path = "../../middleware/script_objs", features = [
    "makepad",
], default-features = false }
#   /Users/user/Downloads/makepad-rik/widgets
gen_dyn_run = { path = "../../middleware/dyn" }
gen_plugin = { path = "../../middleware/plugins/plugin" }
ra_ap_syntax = "0.0.258"
