[package]
name = "gen_analyzer"
version = "0.1.0"
edition = "2021"
authors = ["Will SHENG<syf20020816@outlook.com>"]
description = "syntax analyzer for genui"
license = "MIT"
repsitory = "https://github.com/Privoce/GenUI"
keywords = ["genui", "analyzer", "syntax", "parser"]

[features]
default = ["makepad", "base"]
base = []
makepad = []
full = ["makepad", "base"]

[dependencies]
nom = "7.1.3"
serde_json = "1.0.120"

gen_utils = { path = "../utils", features = [
    "parser", "common"
], default-features = false }
# gen_utils = { version = "0.1.1", features = [
#     "parser",
#     "common",
# ], default-features = false }
