[package]
name = "gen_analyzer"
version = "0.1.0"
edition = "2021"

[features]
default = ["makepad", "base"]
base = []
makepad = []
full = ["makepad", "base"]

[dependencies]
nom = "7.1.3"
serde_json = "1.0.120"

gen_utils = { path = "../utils", features = [
    "common",
], default-features = false }
