[package]
name = "gen_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
serde_json = "1.0.120"

gen_utils = { path = "../utils", features = [
    "common",
], default-features = false }
