[package]
name = "ark_gen_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
gen_converter = { path = "../../converter" }
gen_utils = { path = "../../utils" }
gen_parser ={ path = "../../parser"}
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52", features = ["full", "extra-traits"] }
which = "6.0.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.120"
toml_edit = "0.22.12"