[workspace]
members = [
    "analyzer",
    "generator/makepad",
    # "generator/ark",
    "utils",
    "macros",
    "traits",
    "middleware/rssyin",
    # "components",
    # "middleware"
    # "middleware/script_objs",
    "middleware/plugins/macro",
    "tests",
    "middleware/plugins/plugin",
    "middleware/dyn",
]
