[package]
name = "gen_parser"
version = "0.1.0"
edition = "2021"
authors = ["Will SHENG<syf20020816@outlook.com>"]
description = "parsers for gen (Template, Style, Script)"
license = "MIT"
repsitory = "https://github.com/Privoce/GenUI"
keys = ["genui", "parser"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["makepad", "base"]
base = []
makepad = []
full = ["makepad", "base"]

[dependencies]
nom = "7.1.3"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52", features = ["full", "extra-traits"] }
serde_json = "1.0.120"

gen_utils = { path = "../utils", features = [
    "parser",
    "error",
    "common",
], default-features = false }
# gen_utils = { version="0.1.0", features = [
#     "parser",
#     "error",
#     "common",
# ], default-features = false }

