[package]
name = "gen_mk_script_objs"
version = "0.1.0"
edition = "2021"
description = "only for support needed structs for gen script and give these structs to the rssyin to handle"
authors = ["Will Sheng <syf20020816@outlook.com>"]
license = "MIT"
repsitory = "https://github.com/Privoce/GenUI"
keys = ["makepad", "genui", "middleware"]

[features]
default = ["makepad"]
makepad = []

[dependencies]
syn = "2.0.85"
proc-macro2 = "1.0.89"
quote = "1.0.37"
# gen_utils = { path = "../../utils", features = [
#     "common",
# ], default-features = false }
# gen_converter = { path = "../../converter" }
gen_utils = "0.1.0"
gen_converter = "0.1.0"
